package review_test

import (
	"testing"

	"github.com/cristian-fleischer/crobot/internal/platform"
	"github.com/cristian-fleischer/crobot/internal/review"
)

func TestDedupeFindings(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name          string
		findings      []platform.ReviewFinding
		existing      []platform.Comment
		wantNewCount  int
		wantDupeCount int
	}{
		{
			name: "no existing comments - all new",
			findings: []platform.ReviewFinding{
				{Path: "a.go", Line: 1, Side: "new", Severity: "warning", Category: "bug", Message: "msg1", Fingerprint: "fp-1"},
				{Path: "b.go", Line: 2, Side: "new", Severity: "error", Category: "bug", Message: "msg2", Fingerprint: "fp-2"},
			},
			existing:      []platform.Comment{},
			wantNewCount:  2,
			wantDupeCount: 0,
		},
		{
			name: "all findings are duplicates",
			findings: []platform.ReviewFinding{
				{Path: "a.go", Line: 1, Side: "new", Severity: "warning", Category: "bug", Message: "msg1", Fingerprint: "fp-1"},
			},
			existing: []platform.Comment{
				{ID: "c1", Body: "some text\n\n[//]: # \"crobot:fp=fp-1\"", IsBot: true},
			},
			wantNewCount:  0,
			wantDupeCount: 1,
		},
		{
			name: "some duplicates some new",
			findings: []platform.ReviewFinding{
				{Path: "a.go", Line: 1, Side: "new", Severity: "warning", Category: "bug", Message: "msg1", Fingerprint: "fp-1"},
				{Path: "b.go", Line: 2, Side: "new", Severity: "error", Category: "bug", Message: "msg2", Fingerprint: "fp-2"},
				{Path: "c.go", Line: 3, Side: "new", Severity: "info", Category: "style", Message: "msg3", Fingerprint: "fp-3"},
			},
			existing: []platform.Comment{
				{ID: "c1", Body: "text [//]: # \"crobot:fp=fp-1\"", IsBot: true},
				{ID: "c2", Body: "text [//]: # \"crobot:fp=fp-3\"", IsBot: true},
			},
			wantNewCount:  1,
			wantDupeCount: 2,
		},
		{
			name: "matching via Comment.Fingerprint field",
			findings: []platform.ReviewFinding{
				{Path: "a.go", Line: 1, Side: "new", Severity: "warning", Category: "bug", Message: "msg1", Fingerprint: "fp-1"},
			},
			existing: []platform.Comment{
				{ID: "c1", Body: "no fp tag here", Fingerprint: "fp-1", IsBot: true},
			},
			wantNewCount:  0,
			wantDupeCount: 1,
		},
		{
			name:          "empty findings",
			findings:      []platform.ReviewFinding{},
			existing:      []platform.Comment{},
			wantNewCount:  0,
			wantDupeCount: 0,
		},
		{
			name: "finding with no fingerprint gets auto-generated",
			findings: []platform.ReviewFinding{
				{Path: "a.go", Line: 1, Side: "new", Severity: "warning", Category: "bug", Message: "unique message"},
			},
			existing:      []platform.Comment{},
			wantNewCount:  1,
			wantDupeCount: 0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			newFindings, duplicates := review.DedupeFindings(tt.findings, tt.existing)

			if len(newFindings) != tt.wantNewCount {
				t.Errorf("new findings count: got %d, want %d", len(newFindings), tt.wantNewCount)
			}
			if len(duplicates) != tt.wantDupeCount {
				t.Errorf("duplicates count: got %d, want %d", len(duplicates), tt.wantDupeCount)
			}
		})
	}
}

func TestDedupeFindings_AutoGeneratedFingerprint(t *testing.T) {
	t.Parallel()

	findings := []platform.ReviewFinding{
		{Path: "a.go", Line: 1, Side: "new", Severity: "warning", Category: "bug", Message: "unique message"},
	}

	newFindings, _ := review.DedupeFindings(findings, nil)
	if len(newFindings) != 1 {
		t.Fatalf("expected 1 new finding, got %d", len(newFindings))
	}

	// The finding should now have a fingerprint assigned.
	if newFindings[0].Fingerprint == "" {
		t.Error("expected auto-generated fingerprint, got empty string")
	}
}

func TestDedupeFindings_AutoGeneratedFingerprintMatchesExisting(t *testing.T) {
	t.Parallel()

	// Create a finding without a fingerprint and generate what it would be.
	f := platform.ReviewFinding{
		Path: "a.go", Line: 1, Side: "new", Severity: "warning",
		Category: "bug", Message: "unique message",
	}
	expectedFP := review.GenerateFingerprint(&f)

	findings := []platform.ReviewFinding{f}
	existing := []platform.Comment{
		{ID: "c1", Body: "text [//]: # \"crobot:fp=" + expectedFP + "\"", IsBot: true},
	}

	newFindings, duplicates := review.DedupeFindings(findings, existing)
	if len(newFindings) != 0 {
		t.Errorf("expected 0 new findings, got %d", len(newFindings))
	}
	if len(duplicates) != 1 {
		t.Errorf("expected 1 duplicate, got %d", len(duplicates))
	}
}

func TestGenerateFingerprint(t *testing.T) {
	t.Parallel()

	f := platform.ReviewFinding{
		Path:    "src/main.go",
		Side:    "new",
		Line:    42,
		Message: "test message",
	}

	fp := review.GenerateFingerprint(&f)

	// Check format: path:side:line:hash
	if fp == "" {
		t.Fatal("fingerprint should not be empty")
	}

	// Should be deterministic.
	fp2 := review.GenerateFingerprint(&f)
	if fp != fp2 {
		t.Errorf("fingerprint not deterministic: %q != %q", fp, fp2)
	}

	// Different message should produce different fingerprint.
	f2 := f
	f2.Message = "different message"
	fp3 := review.GenerateFingerprint(&f2)
	if fp == fp3 {
		t.Error("different messages should produce different fingerprints")
	}
}

func TestExtractFingerprint(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		body string
		want string
	}{
		{
			name: "standard fingerprint",
			body: "some text\n\n[//]: # \"crobot:fp=abc123\"",
			want: "abc123",
		},
		{
			name: "fingerprint with colons",
			body: "text [//]: # \"crobot:fp=path.go:new:42:deadbeef\"",
			want: "path.go:new:42:deadbeef",
		},
		{
			name: "no fingerprint",
			body: "just a plain comment",
			want: "",
		},
		{
			name: "empty body",
			body: "",
			want: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			got := platform.ExtractFingerprint(tt.body)
			if got != tt.want {
				t.Errorf("ExtractFingerprint(%q) = %q, want %q", tt.body, got, tt.want)
			}
		})
	}
}
